# Generated by Django 4.2.1 on 2023-05-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admission_number',
            field=models.IntegerField(null=True),
        ),
    ]
