# Generated by Django 4.2.1 on 2023-06-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avtivity',
            new_name='Activity',
        ),
    ]
