# Generated by Django 4.2.1 on 2023-05-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=models.CharField(choices=[('B22ECA', 'A'), ('B22ECB', 'B')], default='M', max_length=7),
        ),
    ]
