# Generated by Django 4.2.1 on 2023-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customuser_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=models.CharField(choices=[('A', 'B22ECA'), ('B', 'B22ECB')], default='M', max_length=7),
        ),
    ]
