# Generated by Django 4.2.1 on 2023-05-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('A', 'Advisor')], default='S', max_length=7),
        ),
    ]
